default: &default
  adapter: postgresql
  encoding: unicode
  pool: 100
  host: localhost
  #username: username
  #password: password

development:
  <<: *default
  database: stock_analysis_development

test:
  <<: *default
  database: stock_analysis_test

production:
  <<: *default
  database: stocks_production
  username: stocks
  password: stocks
  host: localhost
  port: 5432